### ISSUE TITLE
v-show on custom-control does not work

### ISSUE THREAD

**Issue by cadilhac** [inocan-group/vue3-google-map#172]
I was trying to show/hide a custom control like this:

````
<custom-control v-show="canShow">
</custom-control>
````

This does not work. It works only if v-show is applied to a child node of custom-control. Is it intended?

**Comment by HusamIbrahim** [comment]
You'd have to use `v-if` instead

**Comment by HusamIbrahim** [comment]
Your `v-show` is conflicting with a `v-show` we already have on the root div of the component.

`v-if` gets around that because it triggers our logic to create/remove the custom control from the map when the component is created/destroyed.

I'll push a fix for this but in general most of our components will require `v-if` because vue isn't really rendering anything, just instantiating and removing map objects (the only exception being custom controls, custom markers and info windows). `v-show` works by setting `display: none` via inline styles on DOM elements which vue controls.
