### ISSUE TITLE
No map controls with v0.8.1

### ISSUE THREAD

**Issue by JoseGoncalves** [inocan-group/vue3-google-map#48]
Upgrading to v0.8.1 I don't have the map controls overlayed on my map and I'm unable to zoom in/out or drag the map.
You can check my usage demo at https://github.com/JoseGoncalves/vue-google-maps .
This demo works fine with v0.8.0, but it does not work with v0.8.1.

**Comment by JoseGoncalves** [comment]
@dblythy I confirm that. Setting `:keyboard-shortcuts="true"` also enables back the zoom controls with `+` and `- ` keys. Nevertheless setting `:disable-default-ui="false"` does not bring back the default UI controls.

**Comment by JoseGoncalves** [comment]
It seems the default UI prop has incorrect casing set. It's defined as [disableDefaultUi](https://github.com/inocan-group/vue3-google-map/blob/develop/src/components/GoogleMap.vue#L67), when it should be defined as [disableDefaultUI](https://developers.google.com/maps/documentation/javascript/reference/map#MapOptions.disableDefaultUI).

**Comment by dblythy** [comment]
I can fix that in my PR if you would like 😊

**Comment by JoseGoncalves** [comment]
@dblythy Go ahead! Your current PR should fix the current issue, but adding the default UI prop correct name would allow the possibility to disable those controls.

**Comment by HusamIbrahim** [comment]
Thanks for looking into this guys :pray:

> It seems the default UI prop has incorrect casing set. It's defined as [disableDefaultUi](https://github.com/inocan-group/vue3-google-map/blob/develop/src/components/GoogleMap.vue#L67), when it should be defined as [disableDefaultUI](https://developers.google.com/maps/documentation/javascript/reference/map#MapOptions.disableDefaultUI).

One thing to note is that we do need this prop name to remain the same. Otherwise people will have to use `disable-default-u-i` for the kebab case version:
https://vuejs.org/v2/guide/components-props.html#Prop-Casing-camelCase-vs-kebab-case

So a fix would probably have to be in `resolveOptions`:
https://github.com/inocan-group/vue3-google-map/blob/develop/src/components/GoogleMap.vue#L212
