### ISSUE TITLE
Is it possible to make sure map zooms out so all markers are visible?

### ISSUE THREAD

**Issue by web-programmer-here** [inocan-group/vue3-google-map#57]
If I add the markers, they are not all visible on the map, how can I make sure the markers are all visible if that means zooming out or zooming into the map? also is there any auto center without specifying auto center if we have multiple items?

**Comment by HusamIbrahim** [comment]
Hey @web-programmer-here there's currently no auto centering/zooming functionality. I'm afraid you'll have to do it manually. Have you seen this method in the native API? Should be useful:
https://developers.google.com/maps/documentation/javascript/reference/map#Map.fitBounds

**Comment by HusamIbrahim** [comment]
Hi @web-programmer-here 

I haven't used that API before but a quick search turned out this helpful result on Stack Overflow:
https://stackoverflow.com/q/19304574/10341614

So here's an example of what you probably can do:
https://stackblitz.com/edit/vitejs-vite-4tdpur?file=src/components/HelloWorld.vue

**Comment by web-programmer-here** [comment]
thank you, this helped a lot
