### ISSUE TITLE
Heatmap Layer support

### ISSUE THREAD

**Issue by JoseGoncalves** [inocan-group/vue3-google-map#76]
Do you have any plans to add a component for the [Heatmap Layer](https://developers.google.com/maps/documentation/javascript/heatmaplayer)?

**Comment by HusamIbrahim** [comment]
Hey @JoseGoncalves 

Can't say I have plans for that at the moment. There are a couple of other issues that I'd like to prioritize when I have some free time.
If someone wants to take a stab at a PR I'll be happy to provide support. Otherwise will look into this when I'm done with the higher priority items on my list.

**Comment by JoseGoncalves** [comment]
No TS skills here, so I'll not be capable of doing a PR... I'm going to add that support in JS for my current needs and (eagerly) wait for a proper implementation from your side...

**Comment by chemeng** [comment]
Hi @JoseGoncalves, did you get this working using the package (accessing some underlying component/reference) or through the plain vanilla JS implementation?

**Comment by JoseGoncalves** [comment]
Hi @chemeng, still did not hat time to address this... nevertheless, my idea is simply to use the [Advanced Usage](https://vue3-google-map.netlify.app/advanced-usage/) third pattern as a base to initialize and use the Google's [Heatmap Layer](https://developers.google.com/maps/documentation/javascript/heatmaplayer).

**Comment by JoseGoncalves** [comment]
@HusamIbrahim Any idea when you'll have time to implement this feature?

**Comment by HusamIbrahim** [comment]
Hello @JoseGoncalves 

Apologies for the late response. Things were quite busy at work and in my personal life these last couple of weeks. I'll take a stab at this soon hopefully.

**Comment by HusamIbrahim** [comment]
Added in `v0.14.0`. Documentation to be added soon but basic syntax is:

```
  <GoogleMap
    api-key="API_KEY"
    :libraries="['visualization']"
    style="width: 100%; height: 500px"
    :center="center"
  >
    <HeatmapLayer :options="{ data: heatmapData }" />
  </GoogleMap>
```
Note that for convenience you can pass an array of plain lat/lng object literals instead of [LatLng](https://developers.google.com/maps/documentation/javascript/reference/coordinates?hl=en#LatLng) class instances (you can pass those too or mix object literals with `LatLng` instances in the data array if you wish).

Let me know if you notice any bugs.

**Comment by JoseGoncalves** [comment]
Hi @HusamIbrahim. Thanks, I'll test that in the next week.

**Comment by JoseGoncalves** [comment]
Hi @HusamIbrahim. I've tested this and, while it's working, I get some warnings on the browser console:

![Screenshot from 2022-08-30 14-25-10](https://user-images.githubusercontent.com/3037740/187449480-2ae2e101-e441-4b60-911d-2d183b9c5453.png)

You can check a demo project were these warnings occur at: 
* https://github.com/JoseGoncalves/vue-google-maps/tree/heatmap

**Comment by HusamIbrahim** [comment]
Thanks for reporting @JoseGoncalves. Will look into it.
Feel free to create an issue if you wish.

**Comment by HusamIbrahim** [comment]
Fixed in `v0.14.1`

**Comment by chemeng** [comment]
Got it, makes sense. Will probably try the same thing in the next few days.

On Jun 6, 2022, at 11:34 AM, José Miguel Gonçalves ***@***.******@***.***>> wrote:



Hi @chemeng<https://github.com/chemeng>, still did not hat time to address this... nevertheless, my idea is simply to use the Advanced Usage<https://vue3-google-map.netlify.app/advanced-usage/> third pattern as a base to initialize and use the Google's Heatmap Layer<https://developers.google.com/maps/documentation/javascript/heatmaplayer>.

**Comment by chemeng** [comment]
Yes, thank you, we've started using it.
